language: ruby

before_install:
 - gem install bundler

script:
 - bundle exec jekyll build
 
before_deploy:
 - mkdir ~/.ssh
 - chmod go-rwx ~/.ssh
 - cat $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
 - cat $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub
 - chmod go-rwx ~/.ssh/id_rsa
 
deploy:
 - rsync -avc _site/ $SSH_HOST:site/
 
