language: ruby

before_install:
 - gem install bundler

before_script:
 - mkdir -p ~/.ssh
 - chmod go-rwx ~/.ssh
 - echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
 - echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub
 - chmod go-rwx ~/.ssh/id_rsa
 - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

script:
 - bundle exec jekyll build && rsync -avc _site/ $SSH_USER@$SSH_HOST:site/
 
