language: ruby

before_install:
 - gem install bundler
 - sudo apt-get update
 - sudo apt-get install python3

install:
 - sudo pip3 install -r requirements.txt

before_script:
 - mkdir -p ~/.ssh
 - chmod go-rwx ~/.ssh
 - echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
 - echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub
 - chmod go-rwx ~/.ssh/id_rsa
 - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
 - sed -i "s/\\\$GA_ID/$GA_ID/g" _includes/head.html

script:
 - ./run_checks.sh && bundle exec jekyll build && rsync -avc _site/ $SSH_USER@$SSH_HOST:site/
