language: ruby

before_install:
 - gem install bundler
 - curl -sSf --retry 5 -o python-3.8.tar.bz2 ${archive_url}
 - sudo tar xjf python-3.8.tar.bz2 --directory /

install:
 - source ~/virtualenv/python3.8/bin/activate
 - pip install -r requirements.txt
 - bundle install

before_script:
 - mkdir -p ~/.ssh
 - chmod go-rwx ~/.ssh
 - echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
 - echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub
 - chmod go-rwx ~/.ssh/id_rsa
 - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
 - sed -i "s/\\\$GA_ID/$GA_ID/g" _includes/head.html

script:
 - source ~/virtualenv/python3.8/bin/activate
 - ./run_checks.sh && bundle exec jekyll build && rsync -avc _site/ $SSH_USER@$SSH_HOST:site/
