name: Build And Test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.152.0
        with:
          ruby-version: '2.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          bundle install
      - name: Code Style
        run: |
          ./run_checks.sh
      - name: Build
        run: |
          bundle exec jekyll build
